### ISSUE TITLE
Transfer is done twice?

### ISSUE THREAD

**Issue by IanaKhitsko** [bbehrang/Euro-Diffusion#10]
https://github.com/bbehrang/Euro-Diffusion/blob/1e1d36660ed0553aa438c269ae51924a49f7e52e/Grid.js#L85

and 

https://github.com/bbehrang/Euro-Diffusion/blob/1e1d36660ed0553aa438c269ae51924a49f7e52e/Grid.js#L104

Why do you need to call it twice? the same for other neighbors.

**Comment by bbehrang** [comment]
second iteration of transfer was mean to prioritize neighbors that are lacking a specific motif. Since it had no effects on the results, it was removed.
