### ISSUE TITLE
Early return

### ISSUE THREAD

**Issue by IanaKhitsko** [bbehrang/Euro-Diffusion#12]
https://github.com/bbehrang/Euro-Diffusion/blob/1e1d36660ed0553aa438c269ae51924a49f7e52e/Grid.js#L155-L160

Can we return earlier, just right after we found "not complete" country ? 

    checkIfComplete(days){
        this.countries.forEach(country => {
           if(!country.isCompleted) return false;
        });
        return true;
    }

**Comment by bbehrang** [comment]
return was added inside the forEach loop to prevent unnecessary iterations
