### ISSUE TITLE
City transfer question

### ISSUE THREAD

**Issue by ValeronMEN** [bbehrang/Euro-Diffusion#3]
Why have you used a ternary operator here? Why haven't used just "+="?

https://github.com/bbehrang/Euro-Diffusion/blob/1fb670fcf1e79832e6c20837910d4f7bbec00761/City.js#L12

**Comment by bbehrang** [comment]
Because if a motif doesn't exist, its value store at "this.balance[country]" will be undefined and you cant use "+=" on undefined variables.
