### ISSUE TITLE
Coin's two cities path per day

### ISSUE THREAD

**Issue by ValeronMEN** [bbehrang/Euro-Diffusion#6]
https://github.com/bbehrang/Euro-Diffusion/blob/1fb670fcf1e79832e6c20837910d4f7bbec00761/Grid.js#L36

For example, you have 3 cities linked in pairs: 1st with 2nd, 2nd with 3rd
1st - France, 2nd & 3rd - England
Every city has 1 000 000 coins. A representative portion is 1 000.
So due to running a loop through the cities (forEach) it's possible that a coin from the first city will arrive in the third city in one day. 1 000 000 french coins give 1 000 coins to the next city and it gives 1 french coin to all the neigbours. Because the third city is following 2nd and 1st in the loop

I think you have this problem in your program

**Comment by bbehrang** [comment]
According to the task, once the amount of coins of each motif reaches 1000 it can be transferred to another city. I can't seem to understand what is the problem with coins being transferred in a single day if they've reached the required amount.

**Comment by ValeronMEN** [comment]
Mark it as extra help required
