### ISSUE TITLE
Combine conditions

### ISSUE THREAD

**Issue by IanaKhitsko** [bbehrang/Euro-Diffusion#9]
https://github.com/bbehrang/Euro-Diffusion/blob/1e1d36660ed0553aa438c269ae51924a49f7e52e/Program.js#L38-L48

Can be
let isValid = (country.xl > 0 && country.xl <= 10) &&
                   (country.yl > 0 && country.yl <= 10) &&
                   (country.xh > 0 && country.xh <= 10) && 
                   (country.yh > 0 && country.yh <= 10);

?

**Comment by bbehrang** [comment]
Conditions were replaced as was mentioned.
